# Senha de acesso ao app
senha = "veros12345"

[gcp_service_account]
type = "service_account"
project_id = "coletaspop"
private_key_id = "180c8bb8324396683ce16636ddf705a6435829a4"
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
client_email = "acesso-coletas@coletaspop.iam.gserviceaccount.com"
client_id = "110044890589336382285"
auth_uri = "https://accounts.google.com/o/oauth2/auth"  # Fixo
token_uri = "https://oauth2.googleapis.com/token"  # Fixo
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"  # Fixo
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/acesso-coletas@coletaspop.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
