# Senha de acesso ao app
senha = "veros12345"

# Configuração do Google Sheets (substitua pelos seus dados)
[gcp_service_account]
type = "service_account"
project_id = "projeto-veros"
private_key_id = "sua-chave-privada"  # Encontre no JSON
private_key = "-----BEGIN PRIVATE KEY-----\n..."  # Copie TUDO do JSON
client_email = "veros-sheets@projeto-veros.iam.gserviceaccount.com"
client_id = "1234567890"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/...cert_url"