[gcp_service_account]
type = "service_account"
project_id = "coletaspop"
private_key_id = "180c8bb8324396683ce16636ddf705a6435829a4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDfXcxmgNnts3+N
xgrfcz0ZA9yYSNpiroAs+6JsI/B1KBHWoApAalEMexiliSjEc+Ynj7u7kxqb8J+i
ovXEbzkTQE1m1OSS5wS3NgpTEsB6Nnmz00CcL4yRNUWRD0Bv9t4GXK9QWWAc4ZhY
LkbOAbcrDrcKs2vdv6p32god3ZIEYqJneVwszU5yVIUxLcDlHMX1mWuthb9W4M/O
5YJf6ILbJ/vQ/3wl8nLk5q+sjTt6suEvLqqN9F8mcnfN4Gz4PPkBfQB/HoOCofTU
CIONlDnCZZNkeBcUuhTRrHCdXn4OuynvR9HVucbEyeGPQjXo3QaiejJpGMz7Imbl
soml8rhNAgMBAAECggEATxjQonW7dmyrXSGFxSXyO1L+QWD/EJXZptQ+6ot5gYs8
ceO/bZsYc1J94lSlPpgKJvVDlgNcF1+IsBeD71kxfWs2XZVDEfBD37r/wfYwebaj
tzW2Ofiujtct+NXNTDi/28HjhRD5M5EBmSxd/2JlIha2Y9AwgNh3/bQVBAlrxSgd
HOLl0/clEllr9UnhWCsVL9t7Y44Pq1L8rvCPlgFaRTQjgtZa7tZYFbmsgJDFuNKj
zIEQCFxtIaSICxlVKA/DiGnuwP9/Pdm0jeCdGTRaXBI/XmhtNPJ0gsEd6Tz6JVDU
V39XWKY2fdNVFAze4OhLmWH7lrizZtMK79vcsKTTswKBgQDwnE7dyYP0HTNis66C
wUuUdCjqDLoLFcuiTHkpTYn80oxi5k/31DWo8LA/Kjn6P51hOWECvfhtMbulUyeE
v8brhehCjNZDe3wfZ7KkQUL/Q0dmg+HxIkXcnkhAzPF+4wvqI7Tpprwf7ahcVZhU
Se4Up3Nj1O1/xWQV4YXOxWqPowKBgQDtpyOO88fjWmb8D8veFnFnChEJXPYuhEPJ
8JByQpdwp7PDgeNLAvUFFDMPv66BQNDp7VVHvVCV3+Q5L9LgaAQsiGY6b8RlGVgH
6pJHH4QJRDNYI4p569x5Iy9+6yCZELQGGv0p+6s4vYe2Pg9bA1RQU3dPw96AxKZJ
ysnho8BXTwKBgHEU9Vf1SqfjRXBBBGZ9lBjsUwJVAucM0kyv5k3MHGsPRV2B4tmW
CbYhkKPPI7qCRWQZRIe2YthnBErZ/vu76jBtGdCVQmoq0hYsdWAPL/6qTxdWKk1b
Dzx1w315FJLPAJ2FNJSPgWD8ICFtNQ+AQ32/iVLFEu33BmfmOy4HyGJDAoGAQ2H+
jQvGA0qgpJt9/Gx0nviVuAfprWrHJbzV1+/VrJWAPNDZN22RN21wxOhefDt6gLlQ
UtT0wmoG9cf/jK0xcccC5VLHZrr24Ne7vfrLnyz9OeJp4wPjMV2um9fjGENKJ+kD
GyJGfAIRNrUF+ZJKF7RyweURc4VOeOHMt/OMF7UCgYA87ZEyFoZ0RNwWBnDmAi4D
oahBDdMgsD74UaEwnrRX23VNc+A8gH1lIDcG70p4chHdGQjTJLdG7DP9m5pHcqvV
IyIgdaw9fVDW9HRtOCwKnXpNIAyf4iJZmExEqSsrDVzgiYT8a5V+bA6L7wPvbQom
4erCXBo0LDGujTMbpp0tYQ==
-----END PRIVATE KEY-----"""
client_email = "acesso-coletas@coletaspop.iam.gserviceaccount.com"
client_id = "110044890589336382285"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/acesso-coletas%40coletaspop.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
